###
# This file configures the project "Piper" pipeline of your project.
# For a reference of the configuration concept and available options, please have a look into its documentation.
#
# The documentation for the most recent pipeline version can always be found at:
#    https://www.project-piper.io/
#
# This is a YAML-file. YAML is an indentation-sensitive file format. Please make sure to properly indent changes to it.
###



### General project setup
general:
  inferBuildTool: true

### Step-specific configuration
steps:
  npmExecuteScripts: # to do not execute script
    runScripts: []
  mavenExecute:
    dockerImage: devxci/mbtci:1.0.14

  artifactPrepareVersion:
    versioningType: cloud_noTag

### Stage-specific configuration
stages:
  build:
    npmInstall: true
    npmScript: build
  deploy:
    cfApiEndpoint: https://api.cf.us10-001.hana.ondemand.com
    cfOrg: f86034d7-b0fe-49c7-8c42-3b043a384f18
    cfSpace: 32802711-1e00-4aee-8ab6-b158273793f8
    cfCredentialsId: cf
  'Confirm':
    manualConfirmation: false

#  Integration:
#    credentials:
#      - alias: 'mySystemAlias'
#        credentialId: 'mySystemCredentialsId'

#  Release:
#    cfTargets:
#      - org: 'myOrg'
#        space: 'mySpace'
#        apiEndpoint: 'https://'
#        appName: 'myAppName'
#        manifest: 'manifest.yml'
#        credentialsId: 'myDeploymentCredentialsId'
